name: ğŸ’» CI/CD

on:
    push:
        branches: [main]

jobs:
    cicd:
        runs-on: ubuntu-latest
        steps:
            - name: ğŸšš Get latest code
              uses: actions/checkout@v3

            - name: ğŸ“— Setup NodeJS
              uses: actions/setup-node@v3
              with:
                  node-version: "lts/gallium"

            - name: ğŸ”¨ Build Project
              run: |
                  npm install
                  npm run build

            - name: ğŸ§ª Test Project
              run: |
                  npm run test

            - name: ğŸš€ Deploy Project
              uses: JamesIves/github-pages-deploy-action@v4.4.1
              with:
                  branch: gh-pages
                  folder: build
