name: ğŸ‰ Build & Deploy
on:
  push:
    branches:
      - main
    paths:
      - '.github/**'
      - 'src/**'
      - 'public/**'
      - '**.json'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸšš Get latest code
        uses: actions/checkout@v2.3.1

      - name: ğŸ“— Use NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '16.13.0'

      - name: ğŸ”¨ Build Project
        run: |
          npm run preinstall
          npm install
          npm run build

      - name: ğŸš€ Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages
          folder: build